### ISSUE TITLE
Update repo name

### ISSUE THREAD

**Issue by meeech** [argoproj-labs/rollouts-plugin-trafficrouter-contour#12]
Hey @wilsonwu & @izturn 

Just wanted to make you aware of https://github.com/argoproj/argo-rollouts/issues/2720

We are updating the naming convention for plugins for rollouts. 

So in your case, the repo would need to move to rollouts-plugin-trafficrouter-contour

I hope this isn't too much of an inconvenience.

**Comment by wilsonwu** [comment]
Thanks for this notice, no problem for this change.

**Comment by wilsonwu** [comment]
Both repo name and name in code updated.
