### ISSUE TITLE
Implement VerifyWeight function

### ISSUE THREAD

**Issue by mvgmb** [argoproj-labs/rollouts-plugin-trafficrouter-contour#22]
## Summary

Argo Rollouts [weight verification feature](https://github.com/argoproj/argo-rollouts/issues/701) allows the controller to verify the traffic routers after the `setWeight` step. This is useful to avoid problems when the Contour controller is unavailable or has issues updating the HTTPProxy.

## Motivation

Currently, the plugin does not make any verification regarding this feature, as seen below:

https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-contour/blob/bbfbd96f0dd66fa656ad7f7fd383ba7457e97440/pkg/plugin/plugin.go#L146-L148

## Proposal

This verification can be implemented by looking at the `status` field of the HTTPProxy resource since the Contour operator constantly keeps it up-to-date with the proxy's current state.

**Comment by izturn** [comment]
Nice, I will implement it later
