### ISSUE TITLE
[Feature] ARM architecture support 

### ISSUE THREAD

**Issue by yyzxw** [argoproj-labs/rollouts-plugin-trafficrouter-contour#40]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wilsonwu** [comment]
Thanks for the issue, this plugin support ARM (from source code build), but for the artifact, currently the 0.2.0 is not published (some stability problems), in 0.2.0 version artifact it will support ARM, so if you want use ARM version, please build it in your ARM machine from source code.

**Comment by wilsonwu** [comment]
https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-contour/releases/tag/v0.2.0
The latest version released with ARM support.
